/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopiii_lecture_iii;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Desire Kaleba
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    
    String SID;
    
    
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOthername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_id = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_surname = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        list_othername = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        list_sex = new javax.swing.JList<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                frmMain.this.windowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("New Student Registration");

        jLabel2.setText("Sur Name");

        jLabel3.setText("Other Name");

        jLabel4.setText("Sex");

        buttonGroup1.add(rdbMale);
        rdbMale.setText("Male");

        buttonGroup1.add(rdbFemale);
        rdbFemale.setText("Female");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        list_id.setBorder(javax.swing.BorderFactory.createTitledBorder("SID"));
        list_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_idMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list_id);

        list_surname.setBorder(javax.swing.BorderFactory.createTitledBorder("Surname"));
        jScrollPane4.setViewportView(list_surname);

        list_othername.setBorder(javax.swing.BorderFactory.createTitledBorder("Othername"));
        jScrollPane5.setViewportView(list_othername);

        list_sex.setBorder(javax.swing.BorderFactory.createTitledBorder("Sex"));
        jScrollPane6.setViewportView(list_sex);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(rdbMale)
                            .addComponent(rdbFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOthername, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOthername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMale)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbFemale)
                    .addComponent(btnUpdate))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane2))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String strSurname = txtSurname.getText().trim();
        String strOthername = txtOthername.getText().trim();
        String strSex;
        
        if(strSurname.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Sur Name!");
            txtSurname.requestFocus();
            return;
        }
        
        if(strOthername.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Other Name!");
            txtOthername.requestFocus();
            return;
        }
        
        if(rdbMale.isSelected())
            strSex = "Male";
        else if(rdbFemale.isSelected())
            strSex = "Female";
        else{
            JOptionPane.showMessageDialog(this, "Please Select Sex!");
            return;
        }
           
        
        String url = "jdbc:mysql://localhost/iuea";
        String user = "root";
        String pass = "";
        
        try{
            Connection con = DriverManager.getConnection(url, user, pass);
            
            String query = "INSERT INTO bioinfo(surname, othername, sex) VALUES (?, ?, ?)";
            
            PreparedStatement pSt = con.prepareStatement(query);
            
            pSt.setString(1, strSurname);
            pSt.setString(2, strOthername);
            pSt.setString(3, strSex);
            
            pSt.execute();
            
            JOptionPane.showMessageDialog(this, "Student Successfully Saved!");
            
            txtSurname.setText("");
            txtOthername.setText("");
            rdbMale.setSelected(false);
            rdbFemale.setSelected(false);
            
            loadBioinfo();
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void windowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpened
        // TODO add your handling code here:
        loadBioinfo();
    }//GEN-LAST:event_windowOpened

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         String url = "jdbc:mysql://localhost/iuea";
        String user = "root";
        String pass = "";
        
        try{
            Connection con = DriverManager.getConnection(url, user, pass);
            
            String query = "DELETE FROM bioinfo WHERE sid = ?";
            
            
            if(SID == null){
                JOptionPane.showMessageDialog(this, "Please Select a Record to Delete! (from the SID column)");
                return;
            }
            
            //String strSID = String.valueOf(index);
            
            PreparedStatement pSt = con.prepareStatement(query);
            pSt.setString(1, SID);
            pSt.execute();
            
            JOptionPane.showMessageDialog(this, "Student Successfully Deleted!");
            
            loadBioinfo();
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        String strSurname = txtSurname.getText().trim();
        String strOthername = txtOthername.getText().trim();
        String strSex;
        
        if(strSurname.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Sur Name!");
            txtSurname.requestFocus();
            return;
        }
        
        if(strOthername.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Other Name!");
            txtOthername.requestFocus();
            return;
        }
        
        if(rdbMale.isSelected())
            strSex = "Male";
        else if(rdbFemale.isSelected())
            strSex = "Female";
        else{
            JOptionPane.showMessageDialog(this, "Please Select Sex!");
            return;
        }
           
        
        String url = "jdbc:mysql://localhost/iuea";
        String user = "root";
        String pass = "";
        
        try{
            Connection con = DriverManager.getConnection(url, user, pass);
            
            String query = "UPDATE bioinfo SET surname = ?, othername = ?, sex = ? WHERE sid = ?";
            
            PreparedStatement pSt = con.prepareStatement(query);
            
            pSt.setString(1, strSurname);
            pSt.setString(2, strOthername);
            pSt.setString(3, strSex);
            pSt.setString(4, SID);
            
            pSt.execute();
            
            JOptionPane.showMessageDialog(this, "Student Successfully Updated!");
            
            txtSurname.setText("");
            txtOthername.setText("");
            rdbMale.setSelected(false);
            rdbFemale.setSelected(false);
            SID = null;
            
            loadBioinfo();
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void list_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_idMouseClicked
        // TODO add your handling code here:
        String index = list_id.getSelectedValue();
        SID = index;
        
    }//GEN-LAST:event_list_idMouseClicked

    
    private void loadBioinfo(){
        
        String url = "jdbc:mysql://localhost/iuea";
        String user = "root";
        String pass = "";
        
        try{
            Connection con = DriverManager.getConnection(url, user, pass);
            
            String query = "SELECT * FROM bioinfo";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            DefaultListModel id_model = new DefaultListModel();
            DefaultListModel surname_model = new DefaultListModel();
            DefaultListModel othername_model = new DefaultListModel();
            DefaultListModel sex_model = new DefaultListModel();
           //model.setRowCount(0);
            
            if(rs.isBeforeFirst()){
                while(rs.next()){
                    String strSID = rs.getString("sid");
                    String strSurname = rs.getString("surname");
                    String strOthername = rs.getString("othername");
                    String strSex = rs.getString("sex");
                    
                    id_model.addElement(strSID);
                    surname_model.addElement(strSurname);
                    othername_model.addElement(strOthername);
                    sex_model.addElement(strSex);
                    
                    
                    //String[] obj = {strSID, strSurname, strOthername, strSex};
                    //model.addRow(obj);
                    list_id.setModel(id_model);
                    list_surname.setModel(surname_model);
                    list_othername.setModel(othername_model);
                    list_sex.setModel(sex_model);
                   
                }
            }else{
                JOptionPane.showMessageDialog(this, "No Students Registered Yet!");
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> list_id;
    private javax.swing.JList<String> list_othername;
    private javax.swing.JList<String> list_sex;
    private javax.swing.JList<String> list_surname;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JTextField txtOthername;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
